### ISSUE TITLE
Bug: Crashing while 2 players have a colossal chest open in lan

### ISSUE THREAD

**Issue by jamzam90** [CyclopsMC/ColossalChests#102] opened 2018-02-25 07:44 UTC
#### Issue type:
- :bug: 
____
#### Short description:
When ever two player in lan are accessing a giant chest the items no longer render in the inventory, when an item is placed in.

#### Expected behaviour:
Being able to use the chest regardless of whom else is accessing it at the time.

#### Actual behaviour:
Crashing when items are inserted while another player is in the chest and items do not show up

#### Steps to reproduce the problem:
0. Colossal chest with items in it
1. Two players
2. Have one player access the chest
3. Then have the other player access the chest and try to insert a item

____
#### Versions:

- This mod: 1.6.8
- CyclopsCore: 0.11.4
- Minecraft: 1.12.2
- Forge: 14.23.2.2618

#### Log file:

https://pastebin.com/xgGVYwFC

**Comment by rubensworks** [comment] 2018-02-25 07:46
I literally _just_ released a new version that fixes this, duplicate of #101. A new version should appear soon on curseforge.

**Closed as completed by rubensworks** 2018-02-25 07:46 UTC
Labels: duplicate

**Comment by jamzam90** [comment] 2018-02-25 07:48
Woops, forgot about the other one and thanks for being so quick, now I just need to wait for the pack thats using it to update.
