### ISSUE TITLE
Duping by scrolling

### ISSUE THREAD

**Issue by OldManCraft** [CyclopsMC/ColossalChests#25] opened 2016-03-01 15:38 UTC
when a stack of something is placed in a chest I can then click down on my scroll wheel and it dupes everything in the chest. There has to be a stack of something in it for it to work. This is on a server. 

Latest version
Latest forge
Have mouse tweeks and inventory Tweeks installed.

**Comment by rubensworks** [comment] 2016-03-01 15:54
Does this bug also exist when mouse tweaks and inv tweaks are _not_ installed?

**Comment by OldManCraft** [comment] 2016-03-01 16:05
That I don't know... Had to remove the Mod from the server. Its the auto sorting button.

**Comment by rubensworks** [comment] 2016-03-16 16:24
Just tried it in both SSP and SMP with Forge 1.8.9-11.15.1.1764, CyclopsCore 0.5.1, ColossalChests 1.3.2, Mouse Tweaks 2.6.1 and Inventory Tweaks 1.60-beta-39.
I was not able to reproduce this duping bug.
So either it is being caused by some other mod, or it was already fixed by Forge, Mouse Tweaks or Inventory Tweaks.

@BuckitHead If the bug still persists, let me know by providing a detailed walkthrough to reproduce the bug.

**Closed as completed by rubensworks** 2016-03-16 16:24 UTC
Labels: bug
