### ISSUE TITLE
[1.12.2] Huge lag when opening chests and looking at the inventory

### ISSUE THREAD

**Issue by fkrisi11** [CyclopsMC/ColossalChests#130] opened 2020-04-12 19:14 UTC
#### Issue type:
Performance issue

#### Short description:
After right clicking a bigger chest (like 20x20x20), it takes a while to actually get the GUI.
After you get the GUI, it's very laggy. (I have 1 fps in a 20x20x20 obsidian chest gui)

#### Steps to reproduce the problem:
1. Build 20x20x20 size obsidian chest
2. Open it to observe the 2 problems

#### Versions:
- This mod: ColossalChests-1.12.2-1.7.3
- Minecraft: 1.12
- Forge: 1.12.2 - 14.23.5.2847

**Comment by rubensworks** [comment] 2020-04-13 07:11
Could you share your profiling output as described here? https://github.com/CyclopsMC/CyclopsCore/blob/master-1.12/.github/CONTRIBUTING.md#performance-issues-snail

<blockquote><img src="https://avatars2.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CyclopsCore">CyclopsMC/CyclopsCore</a></strong></div><div>Minecraft library mod for EvilCraft, Integrated Dynamics and others. - CyclopsMC/CyclopsCore</div></blockquote>

**Comment by fkrisi11** [comment] 2020-04-13 08:19
Where should I upload the files? GitHub says it doesn't like it

**Comment by fkrisi11** [comment] 2020-04-13 08:29
Also... I can only run it on the server it seems, so I did that
I just need to know where to upload the file to

**Comment by rubensworks** [comment] 2020-04-13 09:26
Zipping and uploading should work.

**Comment by fkrisi11** [comment] 2020-04-13 09:45
Ah nice. It works like this.
I hope this will be helpful in finding a solution.

What program do you use to analyze these files by the way? Just out of curiosity.
[server_sample.zip](https://github.com/CyclopsMC/ColossalChests/files/4468972/server_sample.zip)

**Comment by rubensworks** [comment] 2020-04-13 14:23
Thanks!

I use VisualVM to open nps files btw.

**Comment by fkrisi11** [comment] 2020-04-13 14:25
I see. Thanks for that. Just wanted some insight ^^

**Comment by rubensworks** [comment] 2020-04-14 15:12
To be honest, I don't see anything abnormal in the profiling output.

Could you try without any other mods installed? Because another mod may be causing the problem.

**Comment by fkrisi11** [comment] 2020-04-14 18:39
The scrolling performance is still horrible with just worldedit, jei and colossalchests installed.
But the inventory rendering itself is not as bad now with just these mods.
So I'm really not sure what causes this.

**Comment by rubensworks** [comment] 2020-04-15 06:33
Ok, then I'm closing this issue.
Should you (or anyone else) be able to provide more information that would point out this mod as the cause of the performance issue, be sure to let me know here.

**Closed as completed by rubensworks** 2020-04-15 06:33 UTC
Labels: performance, mc-1.12
