### ISSUE TITLE
[1.12.0] Mod Incompatibility with Thut's Elevators

### ISSUE THREAD

**Issue by hextrace** [CyclopsMC/ColossalChests#85] opened 2017-07-01 05:01 UTC
**Minecraft Version:**  1.12.0
**Forge Version:** xxx.2387
**Colossal Chests Version:** 1.6.2
**Cyclops Core Version:** 0.10.7
**Crash Report:** https://paste.ee/p/2Mkfw

**Issue:**
Minecraft fails to load properly and crashes out.

**Details:**
To be fair, the crash report was not very informative; however, I was adding mods 1 by 1 in my 1.12 modpack.  Upon downloading Colossal Chests w/ Cyclops Core is when I received this error.  I disabled Colossal Chests as a test and Minecraft loads fine, even with Cyclops Core enabled.

**Comment by rubensworks** [comment] 2017-07-01 07:51
I can't reproduce this with only CC and ColChest installed, can you?

If not, this must be caused by another mod. Perhaps a coremod you are using.

**Comment by hextrace** [comment] 2017-07-01 08:11
Yeah, there is a mod conflict somewhere -- just not w/ the listed core mods.

**Comment by rubensworks** [comment] 2017-07-01 08:17
Can you identify which one?

**Comment by hextrace** [comment] 2017-07-01 08:35
Working through it right now.

**Comment by hextrace** [comment] 2017-07-01 08:57
Found it.  During phase three Colossal Chests will crash when Thut's Elevators is enabled.

**Comment by rubensworks** [comment] 2017-07-01 08:58
Can you report this to their issue tracker as well, and link back to and from this issue here?

**Comment by hextrace** [comment] 2017-07-01 09:01
Doesn't look like Patnevis has an issue tracker; however, I will report this issue on their Curseforge page.

EDIT: I'm a nub; Curseforge auto-magically puts things into a mobile format when a browser window is sized a certain way.  Found the issue tracker.

**Comment by Thutmose** [comment] 2017-07-01 21:56
Looking into this on my end, not sure what is going on, it looks like it might be an issue related to my EnumType for my lift blocks, I will look into the differences between that EnumType and my others used by Pokecube.

**Comment by Thutmose** [comment] 2017-07-01 22:11
I did find some obsolete stuff that I was doing in the Thut's Elevators code, but even after removing that, it still seems to crash.

The following sets of mods work:
ThutCore 5.0.1
CyclopsCore 0.10.7
Thut's Elevators 6.0.1 (recompile with less crap in the enum)

ThutCore 5.0.1
CyclopsCore 0.10.7
ColossalChests 1.6.2

but this set has that crash
ThutCore 5.0.1
CyclopsCore 0.10.7
ColossalChests 1.6.2
Thut's Elevators 6.0.1 (recompile with less crap in the enum)

Does ColossalChests do anything with the block statemaps?

**Comment by Thutmose** [comment] 2017-07-02 01:08
I have fixed this on my end. 

![image](https://user-images.githubusercontent.com/2363472/27766532-1b2ee5c4-5ea1-11e7-8a0b-e4c21a6b09b5.png)

I have no idea why this was only crashing when your mod was installed, it should have always been crashing... I had a custom state mapper still being registered in preinit.

Uploading fix for my end of this, so you can close the issue.

**Comment by hextrace** [comment] 2017-07-02 01:11
@Thutmose Thank you for taking a look into this and the prompt responses.

**Closed as completed** 2017-07-02 01:17 UTC

**Comment by rubensworks** [comment] 2017-07-02 07:44
@Thutmose Awesome, thanks! :-)
