### ISSUE TITLE
CTD (Crash to desktop) when sort button pressed (Inventory Tweaks mod with Colossal Chest mod v1.5.1

### ISSUE THREAD

**Issue by KusanagiRyu** [CyclopsMC/ColossalChests#80] opened 2017-04-26 13:59 UTC
Hi Ruben, 
As mentioned above and in #68 , CTD occured with 1.5.1 (current latest). here's a pastebin link to it; [HERE](https://pastebin.com/kH1SvRnV).

**Comment by rubensworks** [comment] 2017-04-26 14:01
Duplicate of #77

**Closed as completed by rubensworks** 2017-04-26 14:01 UTC
Labels: duplicate
