### ISSUE TITLE
[1.12.1] Crash when placing via the Builder from RFTools

### ISSUE THREAD

**Issue by Boomflex** [CyclopsMC/ColossalChests#93] opened 2017-09-21 22:21 UTC
Colossal Chests v1.6.5
Cyclops Core v0.10.15
Forge v14.22.0.2464

Crash when placing Colossal Chest blocks with the Builder from RFTools.

https://pastebin.com/TjXHLueA

**Comment by rubensworks** [comment] 2017-09-22 06:30
Duplicate of #92, this was fixed in release 1.6.6.

**Closed as completed by rubensworks** 2017-09-22 06:30 UTC
Labels: duplicate
