### ISSUE TITLE
Broken textures for all chests above wooden tier

### ISSUE THREAD

**Issue by Creatures-5** [CyclopsMC/ColossalChests#133] opened 2020-05-08 20:44 UTC
Visual bug.
All the colossal chests other than wooden have missing texture.

#### Versions:

- ColossalChests: 1.15.2-1.7.7.jar
-IronChests: 1.15.2-10.0.3.jar

- Minecraft: 1.15.2
- Forge: 1.15.2-forge-31.1.41

**Comment by rubensworks** [comment] 2020-05-09 06:15
This is a duplicate of #132, so I'm merging this issue there.
Thanks for reporting!

**Closed as completed by rubensworks** 2020-05-09 06:15 UTC
Labels: duplicate
