### ISSUE TITLE
Right-clicking incomplete chest causes server crash

### ISSUE THREAD

**Issue by Anuuviem** [CyclopsMC/ColossalChests#125] opened 2019-11-15 01:32 UTC
#### Issue type:

- :bug: Bug

____

#### Short description:

Direct instance, one colossal chest wall block placed, right click, crash

#### Steps to reproduce the problem:

1. Place single wall block/incomplete chest
2. Right click on block/incomplete chest
3. Presto!

#### Expected behaviour:

Nothing or text to chat saying chest is incomplete/ number of blocks needed

____

#### Versions:

- This mod: 1.7.4
- Minecraft: 1.14.4
- Forge: 28.1.90

#### Log file:

https://pastebin.com/WENxgQ3Y

**Comment by rubensworks** [comment] 2019-11-15 02:10
Duplicate of #122.

**Closed as completed by rubensworks** 2019-11-15 02:10 UTC
Labels: duplicate
