### ISSUE TITLE
1.10.2 Crash with probably inventorytweaks

### ISSUE THREAD

**Issue by KristjanKr** [CyclopsMC/ColossalChests#77] opened 2017-04-18 12:24 UTC
When opening colossal chest and i clicked middle click button on my mouse, my game crashed with following crashlog:
https://paste.ee/p/4yF1E

if any more info is needed, then im willing to do so.

Also: https://pastebin.com/kH1SvRnV

**Comment by rubensworks** [comment] 2017-04-23 06:09
Is it possible that you're using a mod that changes the player inventory size?

If so, could you try the latest dev build?: https://dl.bintray.com/cyclopsmc/dev/org/cyclops/colossalchests/ColossalChests/1.10.2-1.5.0-156/ColossalChests-1.10.2-1.5.0-156.jar

**Comment by rubensworks** [comment] 2017-04-26 14:01
@KusanagiRyu Is it possible that you're using a mod that changes the player inventory size?

**Comment by KusanagiRyu** [comment] 2017-04-26 14:04
Nope, i seen that mod in Invasion modpack but i'm not using it in this modpack (Forever Stranded), unless you're refering to Bagginses mod and IronBackpack mod...

**Comment by rubensworks** [comment] 2017-04-26 14:06
@KusanagiRyu Can I send you a dev build to try when I can look into it?

**Comment by KusanagiRyu** [comment] 2017-04-26 14:06
the one you offered to KristjanKr?

**Comment by rubensworks** [comment] 2017-04-26 14:07
@KusanagiRyu No, that one is released already. I'll have to make some more changes in the future when I have time for it.

**Comment by KusanagiRyu** [comment] 2017-04-26 14:07
sure. what's the link to it?

**Comment by rubensworks** [comment] 2017-04-26 17:46
I'm not able to reproduce this with the latest IT version on 1.10.
@KusanagiRyu I've added some debug information when it crashes, could you try the following dev build?
https://dl.bintray.com/cyclopsmc/dev/org/cyclops/colossalchests/ColossalChests/1.10.2-1.5.1-165/ColossalChests-1.10.2-1.5.1-165.jar
And send me the full Forge log when it crashes.

**Comment by KusanagiRyu** [comment] 2017-04-27 11:51
Here you go Ruben; [Crash Log](https://pastebin.com/i7c8TydP)

**Comment by rubensworks** [comment] 2017-04-27 11:52
@KusanagiRyu Can you send me the _full_ Forge log? It contains additional debug information.

**Comment by KusanagiRyu** [comment] 2017-04-27 12:05
full? you mean the launcher log? Sure, [here](https://drive.google.com/open?id=0BxtS3Obx6GxjZHFjNllEeEtCUE0)

**Comment by rubensworks** [comment] 2017-04-27 12:09
Thanks, that's it. I'll look into it later today.

**Comment by KusanagiRyu** [comment] 2017-04-27 12:10
Thanks for your time, Ruben

**Comment by rubensworks** [comment] 2017-04-27 18:35
@KusanagiRyu What is the material of your chest? Is it by any chance copper or silver? If not, what are the dimensions of your chest?

**Comment by KusanagiRyu** [comment] 2017-04-29 12:12
Sorry for the delay. It's silver. 5x5x5

**Comment by rubensworks** [comment] 2017-04-29 12:20
@KusanagiRyu Thanks, in that case I know exactly what's going wrong. Should be fixed later today or tomorrow.

**Comment by KusanagiRyu** [comment] 2017-04-29 13:09
Many thanks Ruben

**Comment by rubensworks** [comment] 2017-04-29 16:20
@KusanagiRyu Could you try the latest dev build?
This should resolve the issue.

https://dl.bintray.com/cyclopsmc/dev/org/cyclops/colossalchests/ColossalChests/1.10.2-1.5.1-166/ColossalChests-1.10.2-1.5.1-166.jar

**Comment by KusanagiRyu** [comment] 2017-04-29 16:37
Ok Ruben, tested and it still give me error message, only slightly different; [here](https://drive.google.com/file/d/0BxtS3Obx6GxjWElTY05YZEp0NFU/view?usp=sharing). See you in 10 hours.

**Comment by rubensworks** [comment] 2017-04-29 17:08
@KusanagiRyu I don't see any (colossal chests-related) crash log in there. I also don't see any of the debug information I've added in the previous version.
Could you send me the crash log as well?

**Comment by KusanagiRyu** [comment] 2017-04-30 01:37
It didn't crash, it gave error messages when I sort. Give me a moment I recreate the error to make log.

**Comment by KusanagiRyu** [comment] 2017-04-30 02:57
ok, Ruben; [here](https://drive.google.com/file/d/0BxtS3Obx6GxjMjVrRVNLQ0xiRHc/view?usp=sharing).

**Comment by rubensworks** [comment] 2017-04-30 08:16
@KusanagiRyu Ok, so it's not crashing anymore. In that case this issue is fixed, right?
The sorting not working seems to be #68, which is a not-yet-implemented feature.

**Comment by KusanagiRyu** [comment] 2017-04-30 08:46
i see... back to square one then... oh well... better than nothing. looking for forward to your future stable build.

**Comment by rubensworks** [comment] 2017-04-30 08:49
My priority is always to get crashes like this one fixed.
Implementing the sorting feature is something I hope to get around to soon, but I have a lot of other things I want to implement first.

Thanks for your help!

**Closed as completed by rubensworks** 2017-04-30 08:49 UTC
Labels: bug
